package electronics.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jul 21 13:38:35 UTC 2022]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TurbineGroupPeer
    extends electronics.om.BaseTurbineGroupPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1658410715203L;

}
